[package]
edition = "2024"
name = "demo-ble"
version = "0.1.0"
license = "MIT"
publish = false

[dependencies]
embassy-executor = { version = "0.9.0", features = ["arch-cortex-m", "executor-thread", "executor-interrupt", "defmt"] }
embassy-time = { version = "0.5.0", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-nrf = { version = "0.9.0", features = ["defmt", "nrf54l15-app-s", "time-driver-grtc", "gpiote", "unstable-pac", "time"] }
embassy-futures = "0.1.1"
embassy-sync = { version = "0.7", features = ["defmt"] }

da728x = { path = "../../", features = ["debug"] }
da728x-examples-common = { path = "../../examples/common" }

defmt = "1.0"
defmt-rtt = "1.0"
panic-probe = { version = "1.0", features = ["print-defmt"] }

cortex-m = { version = "0.7", features = ["inline-asm"] }
cortex-m-rt = "0.7"

portable-atomic = "1"
static_cell = "2"

trouble-host = { version = "0.6.0", features = ["derive", "gatt", "peripheral", "default-packet-pool", "defmt"] }
bt-hci = { version = "0.8", default-features = false, features = ["defmt"] }
nrf-sdc = { path = "../../../nrf-sdc/nrf-sdc", default-features = false, features = ["defmt", "peripheral", "nrf54l15-app-s"] }
nrf-mpsl = { path = "../../../nrf-sdc/nrf-mpsl", default-features = false, features = ["defmt", "critical-section-impl"] }

[profile.release]
debug = 2
